apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-dep
  labels:
    app: python-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-dep
  template:
    metadata:
      labels:
        app: python-dep
    spec:
      containers:
        - name: python-dep
          image: <image_uri>
          ports:
            - containerPort: 8000
