apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: secret-app
          image: 
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: "FastAPI with Secrets"
            - name: GREETING
              value: "Secrets Demo in Kubernetes!"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: DB_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: DB_PWD
