apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: monitoringndlogging
  labels:
    k8s-app: log-collector
spec:
  selector:
    matchLabels:
      name: log-collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: log-collector
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
      containers:
      - name: log-collector
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            tail -n+1 -F /var/log/containers/*.log
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
          - name: varlog
            mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
