apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-api
  labels:
    app: py-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-api
  template:
    metadata:
      labels:
        app: py-api
    spec:
      containers:
        - name: py-api
          image: <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/sidecar:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: api-logs
              mountPath: /var/log
        - name: log-container
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["touch /var/log/app.log && tail -f /var/log/app.log"]
          volumeMounts:
            - name: api-logs
              mountPath: /var/log
      volumes:
        - name: api-logs
          emptyDir: {}
