apiVersion: v1
kind: Pod
metadata:
  name: nginx-requ-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values:
                - us-east-1
                - us-east-2
  containers:
    - name: nginx-requ-affinity
      image: nginx