apiVersion: v1
kind: Pod
metadata:
  name: nginx-pref-pod
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - ap-south-1
  containers:
  - name: nginx-pref-pod
    image: nginx