apiVersion: v1
kind: ReplicationController
metadata:
  name: backend-rc
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <image_uri>
        ports:
        - containerPort: 5000
